title: Representative Learning Lab (RLab)
description: Distributed AI via Representative Learning (RepL)
theme: minima

markdown: kramdown

header_pages:
  - research.md
  - publications.md
  - experience.md
  - talks.md

author: Keren Li
